import type { Lead } from "./types"

export const mockLeads: Lead[] = [
  {
    id: "1",
    companyName: "TechStart Solutions",
    contactName: "Sarah Johnson",
    email: "sarah@techstart.com",
    phone: "(555) 123-4567",
    website: "https://techstart.com",
    address: "123 Innovation Dr",
    city: "San Francisco",
    state: "CA",
    zipCode: "94105",
    industry: "Technology",
    businessType: "Software Development",
    employeeCount: "10-50",
    revenue: "$1M-$5M",
    description: "Innovative software solutions for small businesses",
    rating: 8.5,
    status: "prospect",
    tags: ["high-priority", "tech-savvy", "growing"],
    source: "google_maps",
    notes: "Potential client for our enterprise solution",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    companyName: "Green Valley Restaurant",
    contactName: "Mike Chen",
    email: "mike@greenvalley.com",
    phone: "(555) 987-6543",
    website: "https://greenvalley.com",
    address: "456 Main St",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
    industry: "Food & Beverage",
    businessType: "Restaurant",
    employeeCount: "5-10",
    revenue: "$500K-$1M",
    description: "Family-owned restaurant specializing in organic cuisine",
    rating: 7.2,
    status: "contacted",
    tags: ["local-business", "family-owned"],
    source: "google_maps",
    contactedAt: new Date("2024-01-20"),
    notes: "Interested in POS system upgrade",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    companyName: "Fitness First Gym",
    contactName: "Lisa Rodriguez",
    email: "lisa@fitnessfirst.com",
    phone: "(555) 456-7890",
    website: "https://fitnessfirst.com",
    address: "789 Wellness Blvd",
    city: "Miami",
    state: "FL",
    zipCode: "33101",
    industry: "Health & Fitness",
    businessType: "Gym",
    employeeCount: "20-50",
    revenue: "$2M-$5M",
    description: "Premium fitness center with personal training services",
    rating: 9.1,
    status: "replied",
    tags: ["premium", "expanding", "tech-forward"],
    source: "google_maps",
    contactedAt: new Date("2024-01-22"),
    repliedAt: new Date("2024-01-25"),
    notes: "Very interested, scheduled demo for next week",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "4",
    companyName: "Urban Design Studio",
    contactName: "Alex Thompson",
    email: "alex@urbandesign.com",
    phone: "(555) 321-0987",
    website: "https://urbandesign.com",
    address: "321 Creative Ave",
    city: "Portland",
    state: "OR",
    zipCode: "97201",
    industry: "Design",
    businessType: "Creative Agency",
    employeeCount: "5-10",
    revenue: "$1M-$2M",
    description: "Modern design studio specializing in brand identity",
    rating: 6.8,
    status: "prospect",
    tags: ["creative", "boutique"],
    source: "google_maps",
    notes: "May need project management tools",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "5",
    companyName: "MedCare Clinic",
    contactName: "Dr. Jennifer Park",
    email: "jennifer@medcare.com",
    phone: "(555) 654-3210",
    website: "https://medcare.com",
    address: "567 Health St",
    city: "Seattle",
    state: "WA",
    zipCode: "98101",
    industry: "Healthcare",
    businessType: "Medical Practice",
    employeeCount: "10-20",
    revenue: "$3M-$5M",
    description: "Full-service medical clinic with multiple specialties",
    rating: 8.9,
    status: "prospect",
    tags: ["healthcare", "established", "compliance-focused"],
    source: "google_maps",
    notes: "Needs HIPAA-compliant solutions",
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28"),
  },
]

export const industryOptions = [
  "Technology",
  "Healthcare",
  "Food & Beverage",
  "Retail",
  "Manufacturing",
  "Professional Services",
  "Real Estate",
  "Education",
  "Finance",
  "Health & Fitness",
  "Design",
  "Construction",
  "Automotive",
  "Entertainment",
]

export const businessTypeOptions = [
  "Software Development",
  "Restaurant",
  "Retail Store",
  "Medical Practice",
  "Law Firm",
  "Accounting Firm",
  "Real Estate Agency",
  "Gym",
  "Creative Agency",
  "Consulting",
  "Manufacturing",
  "Construction Company",
  "Auto Repair",
  "Salon/Spa",
]

export const employeeCountOptions = ["1-5", "5-10", "10-20", "20-50", "50-100", "100-500", "500+"]

export const revenueOptions = ["Under $500K", "$500K-$1M", "$1M-$2M", "$2M-$5M", "$5M-$10M", "$10M-$50M", "$50M+"]
